# Generated by Django 5.1 on 2024-11-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Friendship Status')),
                ('Pid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='player.players')),
                ('Pid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='player.players')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation', models.TextField(verbose_name='Conversation')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of Message')),
                ('friendid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.friends')),
            ],
        ),
    ]
