# Generated by Django 5.1 on 2024-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_friends_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='lockout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
